
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 11 10:32:09 CEST 2012
//----------------------------------------------------

package compiler.synanal;

/** CUP generated class containing symbol constants. */
public class PascalTok {
  /* terminals */
  public static final int CHAR_CONST = 3;
  public static final int VAL = 37;
  public static final int LTH = 26;
  public static final int FUNCTION = 46;
  public static final int LBRACKET = 14;
  public static final int CONST = 41;
  public static final int CHAR = 8;
  public static final int CASE = 59;
  public static final int SEMIC = 18;
  public static final int INT = 9;
  public static final int ARRAY = 38;
  public static final int FOR = 45;
  public static final int NOT = 31;
  public static final int AND = 20;
  public static final int RECORD = 51;
  public static final int TYPE = 54;
  public static final int NIL = 5;
  public static final int OR = 32;
  public static final int BOOL = 7;
  public static final int COMMA = 11;
  public static final int BEGIN = 40;
  public static final int DIV = 21;
  public static final int GEQ = 23;
  public static final int IF = 47;
  public static final int ASSIGN = 39;
  public static final int UADD = 35;
  public static final int DOT = 12;
  public static final int PTR = 33;
  public static final int OF = 48;
  public static final int DOTS = 13;
  public static final int EOF = 0;
  public static final int RBRACKET = 16;
  public static final int INT_CONST = 4;
  public static final int PROGRAM = 50;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int ADD = 19;
  public static final int LPARENTHESIS = 15;
  public static final int MOD = 29;
  public static final int AUTO = 58;
  public static final int NEQ = 30;
  public static final int GTH = 24;
  public static final int EQU = 22;
  public static final int COLON = 10;
  public static final int ELSE = 43;
  public static final int GOTO = 61;
  public static final int TO = 53;
  public static final int MEM = 27;
  public static final int WHILE = 56;
  public static final int THEN = 52;
  public static final int RPARENTHESIS = 17;
  public static final int LEQ = 25;
  public static final int END = 44;
  public static final int USUB = 36;
  public static final int BOOL_CONST = 2;
  public static final int LABEL = 60;
  public static final int SUB = 34;
  public static final int VAR = 55;
  public static final int PROCEDURE = 49;
  public static final int DO = 42;
  public static final int EXTENDED = 57;
  public static final int IDENTIFIER = 6;

  /* non terminals */
  static final int funcproc_opt = 5;
  static final int var_declarations_record = 30;
  static final int var_declarations2 = 22;
  static final int main_block = 6;
  static final int vardec_opt = 4;
  static final int const_declaration = 8;
  static final int statement = 24;
  static final int extended_opt_ = 26;
  static final int value_list = 21;
  static final int record = 15;
  static final int typedec_opt = 3;
  static final int type = 12;
  static final int statements_opt = 25;
  static final int constdec_opt = 2;
  static final int func = 17;
  static final int parameters = 19;
  static final int array = 16;
  static final int program = 1;
  static final int proc = 18;
  static final int case_ = 32;
  static final int eps = 33;
  static final int labeldef = 29;
  static final int var_declarations = 13;
  static final int labeldefs = 28;
  static final int labeldec_opt_ = 27;
  static final int cases_opt = 31;
  static final int type_declaration = 11;
  static final int source = 0;
  static final int value = 9;
  static final int var_declaration = 14;
  static final int parameters_call = 20;
  static final int var_declaration2 = 23;
  static final int type_declarations = 10;
  static final int const_declarations = 7;
}

